# Generated by Django 4.2.1 on 2023-06-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp1',
        ),
    ]
