# Generated by Django 4.2.1 on 2023-06-03 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_user_otp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='+375290000000', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть введен в формате: '+37529xxxxxxx'. Разрешено до 15 цифр", regex='^\\+37529\\d{7}$')]),
        ),
    ]
