# Generated by Django 4.2.1 on 2023-06-04 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectofinsurance',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец объекта'),
        ),
    ]
