# Generated by Django 4.2.1 on 2023-06-04 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_objectofinsurance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecontract',
            name='ins_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент страхования'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='time_create',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время заключения'),
        ),
    ]
