# Generated by Django 4.2.1 on 2023-06-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_insurancecontract_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectofinsurance',
            name='name',
            field=models.CharField(db_index=True, default='Какой-то объект', max_length=100, verbose_name='Название объекта страхования'),
        ),
    ]
