# Generated by Django 4.2.1 on 2023-06-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_objectofinsurance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecontract',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания договора'),
        ),
    ]
