# Generated by Django 4.2.1 on 2023-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_alter_insurancecontract_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecontract',
            name='total_cost',
            field=models.FloatField(blank=True, help_text='Общая цена услуги', null=True, verbose_name='Общая цена услуги'),
        ),
    ]
