# Generated by Django 4.2.1 on 2023-06-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_alter_insurancecontract_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecontract',
            name='is_activated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активирована ли страховка'),
        ),
    ]
