# Generated by Django 4.2.1 on 2023-06-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_insurancecontract_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectofinsurance',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='ins_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.objectofinsurance', verbose_name='Объект страхования'),
        ),
    ]
