# Generated by Django 4.2.1 on 2023-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_objectofinsurance_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectofinsurance',
            name='cost',
            field=models.IntegerField(verbose_name='Цена объекта'),
        ),
        migrations.AlterField(
            model_name='objectofinsurance',
            name='insured_risks',
            field=models.CharField(choices=[('Высокие', 'High'), ('Нормальные', 'Normal'), ('Низкие', 'Low')], default='Низкие', max_length=11, verbose_name='Категория рисков'),
        ),
    ]
