# Generated by Django 4.2.1 on 2023-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_alter_objectofinsurance_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectofinsurance',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена объекта'),
        ),
    ]
