# Generated by Django 4.2.5 on 2023-09-13 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_alter_objectofinsurance_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecategory',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='objectofinsurance',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Цена объекта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть введен в формате: '+37529xxxxxxx'. Разрешено до 15 цифр", regex='^\\+37529\\d{7}$')]),
        ),
    ]
