# Generated by Django 4.2.5 on 2023-09-13 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_alter_insurancecategory_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceagent',
            name='ins_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insurancebranch', verbose_name='Филиал страхования'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='ins_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insuranceagent', verbose_name='агент страхования'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='ins_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент страхования'),
        ),
        migrations.AlterField(
            model_name='objectofinsurance',
            name='ins_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insurancecategory', verbose_name='Вид страхования'),
        ),
        migrations.AlterField(
            model_name='objectofinsurance',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец объекта'),
        ),
    ]
